server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: tool_check_suggest_search
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/check_suggest_search
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect